---
- name: Creating ansible machines for workshops ran by the BEST instructor in the world (who is me of course)!!
  hosts: localhost
  gather_facts: no
  connection: ssh

  tasks:
    - name: Create machine 0 for the (best!) instructor
      ovirt_vm:
        name: 3_agl_ansible_0
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.10
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student0.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 1 for the (best in the world!) student 
      ovirt_vm:
        name: 3_agl_ansible_1
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.11
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student1.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 2 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_2
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.12
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student2.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 3 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_3
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.13
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student3.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 4 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_4
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.14
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student4.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 5 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_5
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.15
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student5.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 6 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_6
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.16
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student6.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 7 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_7
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.17
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student7.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 8 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_8
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.18
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student8.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 9 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_9
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.19
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student9.lab.redhat.lab
          user_name: root
          root_password: student

    - name: Create machine 10 for the (best in the world!) student
      ovirt_vm:
        name: 3_agl_ansible_10
        template: 3_agl_ansible_tmpt
        state: running
        cluster: Default
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 172.27.3.20
          nic_netmask: 255.255.0.0
          nic_gateway: 172.27.0.1
          nic_name: enp1s0
          nic_on_boot: true
          host_name: student10.lab.redhat.lab
          user_name: root
          root_password: student
